spring:
  datasource:
    hikari:
      maximum-pool-size: 10
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/dep8_notes?createDatabaseIfNotExist=true

  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

    #Here we the name we interted is using to create the database
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


server:
  servlet:
    context-path: /notes
